export function About() {
  return (
    <div className="page about-page">
      <h1>About GRAPES</h1>

      <div className="about-section">
        <h2>What is GRAPES?</h2>
        <p>
          <strong>GRAPES</strong> (Graphical Rendering Alterations for Privacy, Enhancement and
          Stealth) is a browser extension that detects, blocks, and spoofs web surveillance
          technologies. It protects users from session replay recording, browser fingerprinting,
          tracking pixels, DOM monitoring, and visibility tracking.
        </p>
      </div>

      <div className="about-section">
        <h2>What is this dashboard?</h2>
        <p>
          This public dashboard aggregates anonymized surveillance reports voluntarily contributed
          by GRAPES users who opt in. It shows which websites use the most invasive tracking
          technologies, how prevalent each type of surveillance is, and how effectively users are
          blocking it.
        </p>
        <p>
          The goal is accountability: making surveillance practices visible so users can make
          informed choices and sites can be held accountable for their tracking behavior.
        </p>
      </div>

      <div className="about-section">
        <h2>Privacy</h2>
        <p>Data contribution is strictly opt-in. When users choose to participate:</p>
        <ul>
          <li>Only the domain name is shared, never the full URL</li>
          <li>No personal identifiers, IP addresses, or user agents are stored</li>
          <li>Email addresses and IP addresses in evidence strings are stripped</li>
          <li>Timestamps are rounded to the day for k-anonymity</li>
          <li>
            Domains only appear in public stats after reports from multiple distinct days
            (minimum threshold)
          </li>
          <li>The sanitization code is open source for anyone to audit</li>
        </ul>
      </div>

      <div className="about-section">
        <h2>How grades work</h2>
        <p>
          Each domain receives a privacy grade from A (best) to F (worst) based on the total
          number of surveillance reports and the variety of tracking categories detected. A site
          using multiple types of invasive tracking scores worse than one using a single technique.
        </p>
      </div>

      <div className="about-section">
        <h2>Get the extension</h2>
        <p>
          GRAPES is available as a free browser extension for Chrome and Firefox. Install it to
          protect yourself from web surveillance and optionally contribute to this public dataset.
        </p>
      </div>

      <div className="about-section">
        <h2>Methodology</h2>
        <p>
          Reports are generated by GRAPES's real-time detection engine which monitors for known
          surveillance tool signatures, API abuse patterns, and network-level tracking. Each report
          includes the threat category, detection method, confidence level, and whether the threat
          was blocked or just detected. All data undergoes server-side validation and deduplication
          before being included in aggregate statistics.
        </p>
      </div>
    </div>
  );
}
